# Numpy

## Arrays

In [3]:
import numpy as np # Assim vc importa o pacote numpy e dá o apelido de np para ele

lista = [1,2,3,4,5]
vetor = np.array(lista) #Transforma lista em array
print(vetor, type(vetor))

[1 2 3 4 5] <class 'numpy.ndarray'>


## Operations

In [8]:
print('Soma de vetores:', vetor + vetor)
print('Multiplicacao por escalar:', 10*vetor)
# As duas acima funcionam como com vetores normais

print('Produto entre vetores:', vetor*vetor) #Produto termo a termo!
print('Divisao entre vetores:', vetor/vetor)
print('Logaritmo:', np.log(vetor))
print('Exponencial:', np.exp(vetor))



Soma de vetores: [ 2  4  6  8 10]
Multiplicacao por escalar: [10 20 30 40 50]
Produto entre vetores: [ 1  4  9 16 25]
Divisao entre vetores: [1. 1. 1. 1. 1.]
Logaritmo: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


## Some Methods

In [11]:
print('Soma dos termos:', np.sum(vetor))
print('Média:', np.mean(vetor))
print('Soma cumulativa:', np.cumsum(vetor))
print('Encontrar índice com alguma condicao:', np.where(vetor >3)) #Esse cara retorna dois elementos, o primeiro dá os índices do vetor que satisfazem a condicao

Soma dos termos: 15
Média: 3.0
Soma cumulativa: [ 1  3  6 10 15]
Encontrar índice com alguma condicao: (array([3, 4], dtype=int64),)


## Useful Stuff

In [15]:
#Criar um vetor de 5 zeros:
print(np.zeros(5))

#Criar um vetor de 5 uns:
print(np.ones(5))

#Criar um vetor com 5 elementos, que comeca no 0 e vai ate o 10
print(np.linspace(0,10,5))


[ 0.   2.5  5.   7.5 10. ]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


## More Dimensions

In [25]:
# Faz uma matriz 2x2 de zeros
print('Zeros:\n',np.zeros((2,2)))

#Pra fazer uma matriz manualmente
matriz = np.array([[1,2,3],[4,5,6]])
print('Matrix:\n',matriz)

# Pega as dimensoes do array
shape = np.shape(matriz)
print('Dimensoes:',shape)
print('Linhas:', shape[0], 'Colunas:', shape[1])

# Transposta
print('Transposta:')
print(matriz.T)


Zeros:
 [[0. 0.]
 [0. 0.]]
Matrix:
 [[1 2 3]
 [4 5 6]]
Dimensoes: (2, 3)
Linhas: 2 Colunas: 3
Transposta:
[[1 4]
 [2 5]
 [3 6]]
